import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  developingSidebar: [{ type: "autogenerated", dirName: "developing" }],
  cookingSidebar: [{ type: "autogenerated", dirName: "cooking" }],
  shoppingSidebar: [{ type: "autogenerated", dirName: "shopping" }],
  financeSidebar: [{ type: "autogenerated", dirName: "finance" }],
  travelSidebar: [{ type: "autogenerated", dirName: "travel" }],
  miscSidebar: [{ type: "autogenerated", dirName: "misc" }],
};

export default sidebars;
