import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  developingSidebar: [
    { type: "autogenerated", dirName: "developing" },
    {
      type: "doc",
      id: "python/versions",
      label: "🐍 Python",
    },
    {
      type: "doc",
      id: "package-managers/glossary",
      label: "📦 Package Managers",
    },
    {
      type: "doc",
      id: "specifications/country",
      label: "📜 Specifications",
    },
  ],
  packageManagerSidebar: [
    { type: "autogenerated", dirName: "package-managers" },
  ],
  pythonSidebar: [{ type: "autogenerated", dirName: "python" }],
  specificationsSidebar: [{ type: "autogenerated", dirName: "specifications" }],
  cookingSidebar: [{ type: "autogenerated", dirName: "cooking" }],
  financeSidebar: [{ type: "autogenerated", dirName: "finance" }],
  travelSidebar: [{ type: "autogenerated", dirName: "travel" }],
  miscSidebar: [{ type: "autogenerated", dirName: "misc" }],
};

export default sidebars;
