import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  developingSidebar: [{ type: "autogenerated", dirName: "developing" }],
  packageManagerSidebar: [
    { type: "autogenerated", dirName: "package-managers" },
  ],
  pythonSidebar: [{ type: "autogenerated", dirName: "python" }],
  specificationsSidebar: [{ type: "autogenerated", dirName: "specifications" }],
  travelSidebar: [{ type: "autogenerated", dirName: "travel" }],
  miscSidebar: [{ type: "autogenerated", dirName: "misc" }],
};

export default sidebars;
