# ATMs

上哪去領錢...?

| 銀行         | 代碼 | 分行                                                                                        | ATM                                                                                                            | 零錢 ATM                                                                                            |
| ------------ | ---- | ------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- |
| 上海商業銀行 | 011  | [分行查詢](https://www.scsb.com.tw/content/about/about05_a.html)                            | [ATM 查詢](https://www.scsb.com.tw/content/about/about05_a.html)                                               | [零錢 ATM 查詢](https://www.scsb.com.tw/content/about/about05_a.html)                               |
| 台北富邦銀行 | 012  | [分行查詢](https://www.fubon.com/banking/locations/locations.htm)                           | [ATM 查詢](https://www.fubon.com/banking/locations/locations.htm)                                              | -                                                                                                   |
| 國泰世華     | 013  | [分行查詢](https://www.cathaybk.com.tw/cathaybk/personal/contact/locations/#branch)         | [ATM 查詢](https://www.cathaybk.com.tw/cathaybk/personal/contact/locations/#atm)、台北捷運、全家、萊爾富、全聯 | [零錢 ATM 查詢](https://www.cathaybk.com.tw/cathaybk/personal/contact/locations/#atm)               |
| 渣打銀行     | 052  | [分行查詢](https://service.standardchartered.com.tw/location_finder/branch_table/Index)     | [ATM 查詢](https://service.standardchartered.com.tw/location_finder/branch_table/Index)                        | -                                                                                                   |
| 中華郵政     | 700  | [分局查詢](https://www.post.gov.tw/post/internet/I_location/index.jsp?ID=190107)            | [ATM 查詢](https://www.post.gov.tw/post/internet/I_location/index.jsp?ID=190105)                               | -                                                                                                   |
| 聯邦銀行     | 803  | [分行查詢](https://web.ubot.com.tw/map/default.asp?C1=1)                                    | [ATM 查詢](https://web.ubot.com.tw/map/default.asp?C1=2)、萊爾富、桃園、台中、高雄捷運                         | -                                                                                                   |
| 永豐銀行     | 807  | [分行查詢](https://bank.sinopac.com/MMA8/CustomerService/BranchService/branch.html)         | [ATM 查詢](https://bank.sinopac.com/MMA8/CustomerService/BranchService/ATM.html)、萊爾富                       | [零錢 ATM 查詢](https://bank.sinopac.com/MMA8/CustomerService/BranchService/ATM.html)               |
| 玉山銀行     | 808  | [分行查詢](https://www.esunbank.com/zh-tw/about/locations/branch)                           | [ATM 查詢](https://www.esunbank.com/zh-tw/about/locations/atm)、全家                                           | -                                                                                                   |
| 台新銀行     | 812  | [分行查詢](https://www.taishinbank.com.tw/TSB/service-and-support/branch-finder/)           | [ATM 查詢](https://www.taishinbank.com.tw/TSB/service-and-support/atm-location/)、全家、萊爾富、OK             | [零錢 ATM 查詢](https://www.taishinbank.com.tw/TSB/service-and-support/atm-location/)               |
| 中國信託     | 822  | [分行查詢](https://www.ctbcbank.com/twrbo/zh_tw/index/h_locate_index/h_locate_inquiry.html) | [ATM 查詢](https://www.ctbcbank.com/twrbo/zh_tw/index/h_locate_index/h_ATMlocate_inquiry.html)、7-11           | [零錢 ATM 查詢](https://www.ctbcbank.com/twrbo/zh_tw/index/h_locate_index/h_VTMlocate_inquiry.html) |
| 連線商業銀行 | 824  | -                                                                                           | -                                                                                                              | -                                                                                                   |

- [財經公司 - 各銀行 ATM 查詢](https://www.fisc.com.tw/TC/Service?Caid=1f29cc1c-8e5a-4b58-8c2b-869bac580f5c&CaStyleId=14#1)
- [財經公司 - 外幣 ATM](https://www.fisc.com.tw/TC/Download/atmfc.pdf)
- [中央銀行 - 200 元鈔票 ATM](https://www.cbc.gov.tw/public/Attachment/34216221871.pdf)
