# 📄 Documents

List of magical US codes, documents, and their purpose.

| Document     | Type        | Purpose                                                                                                                                                                                                                                                      |
| ------------ | ----------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| 8843         | Form        | Declare non-resident status for tax purposes by F-1 or J-1 visa holders.                                                                                                                                                                                     |
| DE-4         | Form        | Employee's Withholding Allowance Certificate for California <abbr title="Personal Income Tax">PIT</abbr> purposes.                                                                                                                                           |
| F-1          | Visa        | The student visa sticker on the passport.                                                                                                                                                                                                                    |
| I-9          | Form        | Verify the identity and employment authorization of individuals hired for employment in the US.                                                                                                                                                              |
| I-20/DS-2019 | Form        | Form to apply for an F-1/J-1 visa cross the US border.                                                                                                                                                                                                       |
| I-94         | Form        | Arrival-Departure Record Card issued by <abbr title="U.S. Customs and Border Protection">CBP</abbr>.                                                                                                                                                         |
| I-485        | Form        | To apply for permanent resident status                                                                                                                                                                                                                       |
| I-765        | Application | Application to apply for a Form I-766/EAD Card                                                                                                                                                                                                               |
| I-766        | Form/Card   | <abbr title="Employment Authorization Document">EAD</abbr>                                                                                                                                                                                                   |
| I-797        | Form        | Notice of Action regarding UCSIS application.                                                                                                                                                                                                                |
| I-901        | Fee         | SEVIS fee paid by visa applicants (such as F-1, J-1, M-1, etc.) before applying for a visa.                                                                                                                                                                  |
| I-907        | Form        | To request for Premium Processing (expedite) for I-129/I-140/I-539/I-765 Application                                                                                                                                                                         |
| I-931        | Form        | Notice regarding traveling abroad with EAD Combo Card given enclosed with EAD Combo Card.                                                                                                                                                                    |
| W-4          | Form        | Employee's Withholding Certificate for Federal income tax purposes.                                                                                                                                                                                          |
| W-9          | Form        | Provide <abbr title="Taxpayer Identification Number">TIN</abbr> (such as <abbr title="Social Security Number">SSN</abbr>) to entity that will report income to <abbr title="Internal Revenue Service">IRS</abbr> (e.g. Opening an account at stock exchange) |
| I-140        | Form        | Petition submitted by employer to transit an alien worker to become a permanent resident in the US.                                                                                                                                                          |
| 1098-T       | Form        | Proof of tuition payment issued by educational institutions for tax purposes.                                                                                                                                                                                |
